# vim:ft=sh
unbind t
bind-key t run-shell "tmux_close_float && sesh connect \"$(
  sesh list -t | grep -v \"^$(tmux display -p '#S')$\" | grep -v 'float' | fzf-tmux -p 60,40% \
    --layout reverse --info right --keep-right --pointer ' ➜' --color "gutter:#222436,border:#ff966c,label:#ff966c" \
    --no-sort --border-label ' Tmux Sessions ' --prompt '  ' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡ )+reload(sesh list)' \
    --bind 'ctrl-t:change-prompt(  )+reload(sesh list -t)' \
    --bind 'ctrl-d:change-prompt(📁 )+reload(sesh list -z)' \
    --bind 'ctrl-f:change-prompt(🔎 )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-x:execute(tmux kill-session -t {})+change-prompt(  )+reload(sesh list -t)'
)\""

# For old color set --color "gutter:-1"
# --header '  C-a All | C-t Tmux | C-d Zoxide | C-f Find | C-x Kill'
