# help.bash: wt helper functions split out for maintainability.

section() {
  printf '\n%s%s%s\n' "$C_ORANGE" "$1" "$C_RESET"
}

cmd_doc() {
  printf '  %s%-44s%s %s\n' "$C_GREEN" "$1" "$C_RESET" "$2"
}

help_cols() {
  tput cols 2>/dev/null || printf '80'
}

subcmd_doc() {
  # Keep alternative subcommands on separate lines so help mirrors the nested CLI.
  # Wrap only when the current terminal is too narrow for the fixed help column.
  local cmd="$1"
  local desc="$2"
  local indent=4
  local cmd_width=42
  local desc_col=$((indent + cmd_width + 1))
  local cols
  cols=$(help_cols)

  local cmd_len=${#cmd}
  local inline_width=$((indent + cmd_width + 1 + ${#desc}))
  [ "$cmd_len" -gt "$cmd_width" ] && inline_width=$((indent + cmd_len + 1 + ${#desc}))

  if [ "$inline_width" -le "$cols" ]; then
    printf '    %s%-42s%s %s\n' "$C_GREEN" "$cmd" "$C_RESET" "$desc"
  else
    printf '    %s%s%s\n' "$C_GREEN" "$cmd" "$C_RESET"
    printf '%*s%s\n' "$desc_col" '' "$desc"
  fi
}

usage() {
  printf '%swt%s — reusable git worktree helper\n' "$C_BOLD" "$C_RESET"
  printf '%sGit/worktree logic for both terminal and tmux workflows. Tmux wrappers own only UI/session behavior.%s\n' "$C_DIM" "$C_RESET"

  section "Usage"
  printf '  %swt%s <command> [options]\n' "$C_GREEN" "$C_RESET"

  section "Commands"
  cmd_doc 'root [path]' 'Print the main repo root, resolving linked worktrees back to their source repo.'
  cmd_doc 'repos' 'Discover repos under ~/dev, cache them, and manage pinned repos.'
  subcmd_doc 'list [--dev-dir DIR] [--format plain|fzf|json]' 'Print cached repositories.'
  subcmd_doc 'refresh [--dev-dir DIR]' 'Rescan repository directories and update the cache.'
  subcmd_doc 'pin list' 'Print pinned repository paths in picker order.'
  subcmd_doc 'pin toggle <repo>' 'Pin or unpin a repo path relative to the dev directory.'
  cmd_doc 'branches [--fetch]' 'List local + remote branches, deduplicated and picker-friendly.'
  cmd_doc 'worktrees' 'List, create/setup, or remove git worktrees using .ivu config.'
  subcmd_doc 'list [--repo PATH] [--merged] [--format plain|fzf|json]' 'List worktree directories.'
  subcmd_doc 'add <branch|pr-url> [--session NAME] [--base REF] [--fetch] [--local-base] [--repo PATH] [--format text|json]' 'Create/setup a worktree. New branches fetch the latest origin base; --local-base creates from local base and defers sync to the caller.'
  subcmd_doc 'rm <worktree-dir-or-path> [--repo PATH]' 'Remove a worktree.'
  cmd_doc 'config' 'Create or read .ivu.yml/.ivu.yaml worktree settings.'
  subcmd_doc 'init [--repo PATH]' 'Create .ivu.yml from the template if needed.'
  subcmd_doc 'get <key> [--repo PATH]' 'Read a key under worktree.* from repo config.'

  section "Common examples"
  cmd_doc 'wt worktrees add feat/auth' 'Create/setup feat/auth, fetching the configured origin base first when the branch is new.'
  cmd_doc 'wt worktrees add feat/auth --fetch' 'Also fetch to discover feat/auth when no cached remote-tracking ref exists yet.'
  cmd_doc 'wt worktrees add feat/auth --base release/1.2' 'Create feat/auth from local release/1.2, or origin/release/1.2 if local is missing.'
  cmd_doc 'wt worktrees add feat/auth --local-base' 'Create immediately from local base; callers can fetch and merge origin/base after setup.'
  cmd_doc 'wt worktrees add feat/auth --session auth-fix --format json' 'Include a tmux session-name override for wrappers while keeping git setup unchanged.'
  cmd_doc 'wt worktrees list --format fzf' 'List worktrees with merged-status markers for fzf/tmux.'
  cmd_doc 'wt branches --fetch' 'Show current branches immediately, then append newly fetched branches.'
  cmd_doc 'wt config get dir' 'Print the configured worktree root for the current repo.'

  section "Config"
  printf '  Reads %s.ivu.yml%s or %s.ivu.yaml%s at the repo root. Missing config is initialized from %s~/.config/ivu/template.yml%s when adding a worktree.\n' "$C_BLUE" "$C_RESET" "$C_BLUE" "$C_RESET" "$C_BLUE" "$C_RESET"

  section "Completion"
  printf '  Completion descriptions are generated by %swt __complete%s, so tab help stays close to the CLI implementation.\n' "$C_BLUE" "$C_RESET"
  printf '  Try: %swt <tab>%s, %swt worktrees <tab>%s, %swt worktrees add <tab>%s\n' "$C_GREEN" "$C_RESET" "$C_GREEN" "$C_RESET" "$C_GREEN" "$C_RESET"
}

help_repos() {
  section "wt repos"
  cmd_doc 'wt repos list [--dev-dir DIR] [--format plain|fzf|json]' 'Print cached repositories. fzf format includes pin markers.'
  cmd_doc 'wt repos refresh [--dev-dir DIR]' 'Rescan repository directories and update the cache.'
  cmd_doc 'wt repos pin list' 'Print pinned repository paths in picker order.'
  cmd_doc 'wt repos pin toggle <repo>' 'Pin or unpin a repo path relative to the dev directory.'
}

help_branches() {
  section "wt branches"
  cmd_doc 'wt branches [--repo PATH] [--fetch] [--format plain|json]' 'List deduplicated local and origin branches.'
  printf '  %s--fetch%s streams current branches first, fetches in the background, then emits new results.\n' "$C_GREEN" "$C_RESET"
}

help_worktrees() {
  section "wt worktrees"
  cmd_doc 'wt worktrees list [--repo PATH] [--merged] [--format plain|fzf|json]' 'List worktree directories and optional merge status.'
  cmd_doc 'wt worktrees add <branch|pr-url> [--session NAME] [--base REF] [--fetch] [--local-base] [--repo PATH] [--format text|json]' 'Create/setup a worktree using .ivu config, copy_paths, and symlinks. New branches fetch the configured origin base before creation; --local-base uses the local base and marks the JSON metadata for a later sync. Existing local branches fast-forward to origin when safe; --fetch additionally discovers branches with no cached remote-tracking ref. A GitHub PR URL is resolved to its exact head commit via gh (forks add a remote); existing clean PR worktrees fast-forward to that commit. --session passes a tmux session-name override through JSON metadata.'
  cmd_doc 'wt worktrees rm <worktree-dir-or-path> [--repo PATH]' 'Remove a worktree and prune stale git metadata.'
}

help_config() {
  section "wt config"
  cmd_doc 'wt config init [--repo PATH]' 'Create .ivu.yml from the template if no .ivu.yml/.ivu.yaml exists.'
  cmd_doc 'wt config get <key> [--repo PATH]' 'Read a key under worktree.* from repo config.'
  printf '  Keys: %sdir%s, %sbase_branch%s, %scopy_paths%s, %ssymlinks%s, %sstartup_cmd%s, %ssuppress_tmux_startup_hook%s\n' "$C_GREEN" "$C_RESET" "$C_GREEN" "$C_RESET" "$C_GREEN" "$C_RESET" "$C_GREEN" "$C_RESET" "$C_GREEN" "$C_RESET" "$C_GREEN" "$C_RESET"
}

