execute pathogen#infect()

syntax on
filetype on
set number

let mapleader=" "

map <leader>s :source ~/.vimrc<CR>

set hidden
set history=100

filetype indent on
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent

" Remove white space on save
autocmd BufWritePre * :%s/\s\+$//e

" Highlight all words when searching
set hlsearch

" Re-open Previous Open File
nnoremap <Leader><Leader> :e#<CR>

" Show matching parenthesis
set showmatch


