# vim:ft=sh

# Clear 🔔 from window name when switching to it
set-hook -g after-select-window 'run-shell "~/.config/tmux/scripts/clear-bell.sh"'

# Auto-setup windows for git repos
set-hook -g session-created 'run-shell "tmux_git_setup \"#{session_name}\" \"#{pane_current_path}\""'
