# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'laktak/extrakto'

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Ensure hitting <esc> is fast
set -sg escape-time 10

source-file ~/.config/tmux/options.conf
source-file ~/.config/tmux/key_bindings.conf
source-file ~/.config/tmux/plugin_config/sessions.conf
source-file ~/.config/tmux/plugin_config/extrakto.conf
source-file ~/.config/tmux/hooks.conf

# Set theme (run-shell sources color variables then applies shared layout)
# run-shell "~/.config/tmux/scripts/apply-theme.sh ~/.config/tmux/themes/gruvbox.sh"
run-shell "~/.config/tmux/scripts/apply-theme.sh ~/.config/tmux/themes/tokyonight-moon.sh"

# Initialise plugin manager
run '~/.tmux/plugins/tpm/tpm'
