gui:
  sidePanelWidth: 0.5 # gives you more space to show things side-by-side
  theme:
    activeBorderColor:
      - green
      - bold
  nerdFontsVersion: "3"

git:
  # Side by side diff
  # paging:
  #   colorArg: never
  #   pager: ydiff -p cat -s --wrap --width={{columnWidth}}
  paging:
    pager: diff-so-fancy | less --tabs=2 -RFX

keybinding:
  universal:
    nextItem: "n"
    prevItem: "e"
