gui:
  sidePanelWidth: 0.25 # gives you more space to show things side-by-side
  theme:
    activeBorderColor:
      - green
      - bold
  scrollHeight: 20
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always

    # Side by side diff
    pager: delta --dark --paging=never

    # Use gitconfig
    # useConfig: true

keybinding:
  universal:
    nextItem: "n"
    prevItem: "e"
    edit: "E"
    new: "N"
