#
# Link to lazygit configuration file documentation
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
#

gui:
  sidePanelWidth: 0.25 # gives you more space to show things side-by-side
  theme:
    activeBorderColor:
      - green
      - bold
  scrollHeight: 20
  nerdFontsVersion: "3"
  tabWidth: 2
  commitHashLength: 3
  enlargedSideViewLocation: top
  expandFocusedSidePanel: true

git:
  paging:
    colorArg: always

    # Side by side diff
    pager: delta --dark --paging=never

    # Use gitconfig
    # useConfig: true

keybinding:
  universal:
    nextItem: "n"
    prevItem: "e"
    edit: "E"
    new: "N"
    scrollUpMain-alt1: <c-b>
    scrollDownMain-alt1: <c-f>
    filteringMenu: "J" # <c-f> is already used for page down
  files:
    findBaseCommitForFixup: J # <c-f> is already used for page down
    openStatusFilter: K # <c-b> is already used for page down
