gui:
  sidePanelWidth: 0.5 # gives you more space to show things side-by-side
  theme:
    activeBorderColor:
      - green
      - bold

# git:
#   paging:
#     colorArg: never
#     pager: ydiff -p cat -s --wrap --width={{columnWidth}}
#
keybinding:
  universal:
    nextItem: "n"
    prevItem: "e"
# Open nvim when editing files
#os:
#  editCommand: 'nvim'
#  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
