gui:
  sidePanelWidth: 0.5 # gives you more space to show things side-by-side
  theme:
    activeBorderColor:
      - green
      - bold
  nerdFontsVersion: "3"

# git:
#   paging:
#     colorArg: never
#     pager: ydiff -p cat -s --wrap --width={{columnWidth}}
#
keybinding:
  universal:
    nextItem: "n"
    prevItem: "e"
