[mgr]
prepend_keymap = [
  { on = [
    "e",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "n",
  ], run = "arrow 1", desc = "Move cursor down" },
  { on = [
    "i",
  ], run = "enter", desc = "Move cursor down" },
  { on = [
    "h",
  ], run = "leave", desc = "Move cursor down" },
  { on = [
    "<C-f>",
  ], run = "seek 5", desc = "Seek preview forward 5 units" },
  { on = [
    "<C-b>",
  ], run = "seek -5", desc = "Seek preview backward 5 units" },
]

