
add_newline = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = '🌱 '

[git_status]
stashed = ""

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = '${raw}'

# [line_break]
# disabled = true

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
disabled = false

[aws]
disabled = false

[docker_context]
disabled = true

[kubernetes]
disabled = false

# Show only when there is a file containing the below names
detect_files = ["aladdin"]
