# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/ivu/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="powerlevel9k/powerlevel9k"
ZSH_THEME="spaceship"
echo -e "\033]6;1;bg;*;default\a"
# echo -e "\033]6;1;bg;red;brightness;30\a"
# echo -e "\033]6;1;bg;green;brightness;38\a"
# echo -e "\033]6;1;bg;blue;brightness;49\a"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git, zsh-autosuggestions, zsh-syntax-highlighting, wd)
# plugins=(git, zsh-syntax-highlighting, zsh-autosuggestions, cp, wd, z, extract, osx, history, web-search, vi-mode)
plugins=(git zsh-syntax-highlighting zsh-autosuggestions cp wd z extract osx history web-search) #vi-mode)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias cd!='cd $OLDPWD'
# Spoitify
alias pause='spotify pause'
alias play='spotify play'
alias next='spotify next'
alias back='spotify back'

alias hs='hsi'
alias rm='trash'
alias rmdir='trash'
alias rm!='/bin/rm -rv'
alias rmdir!='/bin/rmdir'
alias zs='source ~/.zshrc'
alias copy='pbcopy'
alias paste='pbpaste'
alias cp='cp -Riv'
alias mv='mv -fv'
alias h='history'
alias c='cd'

alias getsize='du -sh'

alias gits='git status'
alias gita='git add'
alias gitl="git log --pretty=format:'%C(yellow)%h %Cred%ad %Cblue%an%Cgreen%d %Creset%s' --date=short"
alias gitc='git commit'

alias tf='terraform'

alias zshrcv='vim ~/.zshrc'
alias zshrca='atom ~/.zshrc'

alias hiddenOn='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hiddenOff='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

alias npr='npm run --silent $*'
alias chrome="open -a 'Google Chrome'"

bindkey '^ ' autosuggest-execute
bindkey '^[ ' autosuggest-accept

proxyOn() {
  export http_proxy=http://localhost:3128
  export https_proxy=http://localhost:3128
  export HTTP_PROXY=http://localhost:3128
  export HTTPS_PROXY=http://localhost:3128
  ln -sf ~/.ssh/config-proxy-on ~/.ssh/config
  echo "Telstra Proxy on"
}
alias on='proxyOn'

proxyOff() {
  unset http_proxy
  unset https_proxy
  unset HTTP_PROXY
  unset HTTPS_PROXY
  ln -sf ~/.ssh/config-proxy-off ~/.ssh/config
  echo "Telstra Proxy off"
}
alias off='proxyOff'

switchAuto() {
  networksetup -switchtolocation Automatic
}

switchWork() {
  networksetup -switchtolocation Work
}

switch () {
  networksetup -switchtolocation $1
}

# Open man page in preview
pman () {
    man -t "${1}" | open -f -a /Applications/Preview.app
}

# title bar color
# echo -e "\033]6;1;bg;red;brightness;153\a"
# echo -e "\033]6;1;bg;green;brightness;191\a"
# echo -e "\033]6;1;bg;blue;brightness;96\a"


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH=/usr/local/bin:$HOME/bin:$PATH
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:/usr/local/Cellar/python/2.7.13_1/bin"
export PATH="$PATH:/usr/local/Cellar/openvpn/2.4.3/sbin"
export PATH="$PATH:/Users/ivu/.bin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbq"

# Python environment manager
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Node version manager
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"


# Start up
proxyOn
# export AWS_DEFAULT_PROFILE=baratheon-utils

# hackathon start up
# export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:/Users/ivu/Telstra/Hackathon/pynaoqi-python2.7-2.1.4.13-mac64
# export PYTHONPATH=${PYTHONPATH}:/Users/ivu/Telstra/Hackathon/pynaoqi-python2.7-2.1.4.13-mac64
# export PYTHONPATH=${PYTHONPATH}:/usr/local/lib/python2.7/site-packages
