version: v0.0.0
log:
  path: /tmp/vi-mongo.log
  level: info
  prettyPrintarstarstt: true
editor:
  commarstarstand: nvim
  env: EDITOR
ui:
  databasePanelWidth: 30
  hello
showConnectionPage: true
showWelcomePage: false
currentConnection: local
connections:
  - url: mongodb://localhost:27017/
    host: localhost
    port: 27017
    database: ""
    username: ""
    password: ""
    name: local
    timeout: 5
    options: {}
styles:
  betterSymbols: true
  currentStyle: dark-blue.yaml
