[tools]
python = "3.12" # [optional] will be used for the venv
golang = "1.22"
nodejs = "22"
ruby = "3.3.4"
node = "latest"

[settings]
# Add support for files like .python-version, .node-version, etc.
idiomatic_version_file_enable_tools = ["python", "node"]
